version: '3.8'

services:
  # Development service
  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: embedding-fe-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "node node_modules/esbuild/install.js && npm run dev"